# Site settings
title: Thomas Vaeth
tagline: Full Stack Web Developer
email: thomas.vaeth@gmail.com
description: Thomas Vaeth is a web developer at Urban Influence in Seattle, Washington.
baseurl: ""
url: "http://thomasvaeth.com"
paginate: 5
paginate_path: "/blog/page-:num"

# Build settings
markdown: kramdown
permalink: pretty

# Default settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true

# Gems
gems: [jekyll-paginate]